name: Numista 1 Countries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 15 * *"   # Runs at 06:00 UTC on the 15th of every month


jobs:
  scrape-countries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Run countries scrape
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          python 1_CurrencyScrapeCode/numista_1_countries.py
